azure_tenant_id       = "#{azure_tenant_id}#"
azure_subscription_id = "#{azure_subscription_id}#"
azure_client_id       = "#{azure_client_id}#"
azure_client_secret   = "#{azure_client_secret}#"
cloudflare_zone_id    = "#{cloudflare_zone_id}#"
cloudflare_api_token  = "#{cloudflare_api_token}#"